engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
      ignore-undeclared: true
      dead-code-detection: true
      backward-compatibility-checks: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.php"

exclude_paths:
- tests/
